nginx:
    build: ./nginx/
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app

php:
    build: ./php/
    ports:
        - 9000:9000
    links:
        - mysql
    volumes_from:
        - app

mysql:
    image: mariadb:latest
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8183:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql

app:
    image: php:7.0-fpm
    volumes:
        - ./public:/var/www/html
    command: "true"


data:
    image: mariadb:latest
    volumes:
        - /var/lib/mysql
    command: "true"
